export const authTexts = {
    brandTagline: 'בשלו ממה שכבר יש לכם בבית.',
    brandSub: 'המזווה עוקב אחרי המלאי והתפוגה, ומציע מתכונים חכמים לפי מה שבאמת נמצא במטבח.',
    signInTitle: 'ברוכים השבים 👋',
    signInSub: 'התחברו כדי לגשת למזווה ולמתכונים שלכם',
    signUpTitle: 'יצירת חשבון 🥕',
    signUpSub: 'כמה פרטים ונתחיל למלא את המזווה',
    email: 'כתובת אימייל',
    password: 'סיסמה',
    fullName: 'שם מלא',
    fullNamePlaceholder: 'נועה לוי',
    forgotPassword: 'שכחת סיסמה?',
    signInBtn: 'כניסה',
    signUpBtn: 'יצירת חשבון',
    continueGoogle: 'המשך עם Google',
    registerGoogle: 'הרשמה עם Google',
    or: 'או',
    noAccount: 'אין לכם חשבון?',
    register: 'הרשמה',
    hasAccount: 'כבר יש לכם חשבון?',
    passwordHint: 'לפחות 8 תווים, אות אחת גדולה ומספר',
    termsPrefix: 'אני מאשר את',
    termsLink: 'תנאי השימוש',
    termsSuffix: 'ומדיניות הפרטיות',
    signInError: 'אימייל או סיסמה שגויים',
    signUpError: 'משהו השתבש, נסה שוב',
    verifyTitle: 'אימות אימייל 📩',
    verifySub: 'שלחנו קוד בן 6 ספרות לכתובת שלכם',
    verifyCodeLabel: 'קוד אימות',
    verifySubmit: 'אימות',
    verifyError: 'קוד שגוי, נסה שוב',
    codeTooShort: 'הקוד קצר מדי, יש להזין 6 ספרות',
    forgotTitle: 'איפוס סיסמה 🔑',
    forgotSub: 'נשלח לכם קוד לאיפוס הסיסמה',
    forgotRequestSubmit: 'שליחת קוד',
    resetCodeLabel: 'קוד איפוס',
    newPassword: 'סיסמה חדשה',
    forgotResetSubmit: 'איפוס סיסמה',
    forgotError: 'משהו השתבש, נסה שוב',
    backToSignIn: 'חזרה להתחברות'
} as const
