export const commonTexts = {
    appName: 'PANTRY',
    save: 'שמירה',
    cancel: 'ביטול',
    delete: 'מחיקה',
    edit: 'עריכה',
    close: 'סגירה',
    confirm: 'אישור',
    continue: 'המשך',
    skip: 'דילוג',
    urlInvalid: 'כתובת רשת לא תקינה',
    selectAll: 'בחירת הכל',
    deselectAll: 'ביטול הכל',
    navHome: 'מזווה',
    navGenerate: 'יצירת מתכון',
    navLibrary: 'המתכונים שלי',
    navHistory: 'היסטוריית בישול',
    navAdd: 'הוספת מצרכים',
    navSettings: 'הגדרות חשבון',
    navLibraryMobile: 'מתכונים',
    navAddMobile: 'הוספה',
    navProfileMobile: 'פרופיל'
}