export const pantryTexts = {
    title: 'המזווה שלי',
    search: 'חיפוש במזווה...',
    emptyTitle: 'המזווה ריק',
    emptySub: 'הוסיפו מוצרים כדי להתחיל',
    addItem: 'הוספת מוצר',
    generateRecipe: '✦ יצירת מתכון',
    greetingPrefix: 'היי,',
    statItemsInStock: 'פריטים במלאי',
    statExpiringSoon: 'מתקלקלים בקרוב',
    statSavedRecipes: 'מתכונים שמורים',
    filterAll: 'הכל',
    typeFilterLabel: 'סוג מוצר',
    typeFilterClear: 'נקה',
    storageLabels: {
        fridge: 'מקרר',
        freezer: 'מקפיא',
        pantry: 'מזווה'
    },
    unitLabels: {
        kg: 'ק"ג',
        g: 'גרם',
        L: 'ליטר',
        ml: 'מל',
        units: 'יחידות'
    },
    unitShortLabels: {
        kg: 'ק"ג',
        g: 'גרם',
        L: 'ליטר',
        ml: 'מל',
        units: 'יח\''
    },
    expiredLabel: 'פג תוקף',
    expiredTodayLabel: 'פג היום',
    validLabel: 'תקף',
    daysLeftLabel: 'ימים',
    noExpiryLabel: 'ללא תאריך',
    noResults: 'לא נמצאו מוצרים תואמים',
    foodTypeLabels: {
        vegetables: 'ירקות',
        fruits: 'פירות',
        dairy: 'מוצרי חלב',
        eggs: 'ביצים',
        meat: 'בשר',
        fish: 'דגים',
        canned: 'שימורים',
        grains: 'דגנים',
        snacks: 'חטיפים',
        beverages: 'משקאות',
        condiments: 'תבלינים ורטבים',
        other: 'אחר'
    },
    addForm: {
        title: 'הוספת מצרך',
        subtitle: 'הוסיפו ידנית, סרקו ברקוד או צלמו קבלה והמערכת תזהה את המוצרים.',
        scanTileTitle: 'סריקת קבלה',
        scanTileSubtitle: 'זיהוי אוטומטי',
        pasteLinkTileTitle: 'הדבקת קישור',
        pasteLinkTileSubtitle: 'קבלה דיגיטלית מקישור',
        pasteTextTileTitle: 'הדבקת טקסט',
        pasteTextTileSubtitle: 'העתיקו טקסט קבלה',
        pasteTextPageTitle: 'הדבקת טקסט קבלה',
        manualEntryTitle: 'הוספה ידנית',
        nameLabel: 'שם המוצר',
        namePlaceholder: 'לדוגמה: קישואים',
        emojiLabel: 'סמל',
        storageLabel: 'מיקום',
        typeLabel: 'סוג מוצר',
        quantityLabel: 'כמות',
        quantityError: 'יש להזין כמות חיובית',
        unitLabel: 'יחידה',
        expiryLabel: 'תאריך תפוגה',
        expiryPlaceholder: 'בחר תאריך',
        suggestionError: 'לא הצלחנו לקבל הצעה',
        suggestionNotRecognized: 'לא זיהינו מוצר מזון בשם הזה',
        suggestionRetry: 'נסה שוב',
        notesLabel: 'הערות (אופציונלי)',
        submit: 'הוספה למזווה',
        submitting: 'מוסיף...',
        saveSuccess: 'המוצר נוסף למזווה',
        suggestionTitle: 'הצעת אחסון ותפוגה חכמה',
        suggestionMatchTitle: (location: string) => (
            `הבחירה שלך מומלצת לאחסון: ${location}`
        ),
        suggestionMismatchTitle: (location: string) => (
            `מומלץ לאחסון: ${location}`
        ),
        currentOptionLabel: (location: string) => (
            `הבחירה הנוכחית · ${location}`
        ),
        recommendedOptionLabel: (location: string) => (
            `ההמלצה · ${location}`
        ),
        selectRecommended: 'בחר',
        expiryEstimateTitle: (location: string, days: number) => (
            `תפוגה ב${location}: ~${days} ימים`
        ),
        applyExpiry: 'קבע תאריך',
        typeRowLabel: 'סוג מוצר',
        typeRowChange: 'שנה',
        typeRowAdd: 'הוסף סוג מוצר +',
        typePickerTitle: 'מה סוג המוצר?',
        typePickerSkip: 'דלג',
        saveError: 'שמירת המוצר נכשלה, נסה שוב'
    },
    duplicateDialog: {
        title: 'המוצר כבר קיים במזווה',
        description: 'כבר יש לכם מוצר בשם זה. תרצו למזג את הכמויות או לשמור כפריט נפרד?',
        merge: 'מיזוג כמויות',
        keepSeparate: 'שמירה כפריט נפרד'
    },
    scanReceipt: 'סריקת קבלה',
    pasteReceipt: 'הדבקת קישור קבלה',
    receiptReview: {
        title: 'סקירת קבלה',
        subtitle: 'בדקו את הפריטים, כווננו כמויות והסירו מה שלא רלוונטי לפני ההוספה.',
        scanTitle: 'מוצרים שזוהו בקבלה',
        scanSourceLabel: 'סריקת קבלה',
        urlTitle: 'מוצרים מהקבלה הדיגיטלית',
        urlSourceLabel: 'קבלה דיגיטלית מקישור',
        textTitle: 'מוצרים מהטקסט שהודבק',
        textSourceLabel: 'קבלה מטקסט',
        itemsDetectedCount: (count: number) => `${count} מוצרים זוהו`,
        deselectAll: 'בטל בחירה',
        rowExpirySoon: (days: number) => `תפוגה בעוד ${days} ימים`,
        editRowTitle: 'עריכת שם המוצר',
        editRowDone: 'סיום',
        uploadPrompt: 'העלו תמונה או PDF של הקבלה',
        uploadHint: 'התמונה מעובדת בשרת ואינה נשמרת',
        uploadButton: 'בחירת קובץ',
        scanning: 'סורק את הקבלה...',
        scanError: 'סריקת הקבלה נכשלה, נסה שוב',
        fileTooLarge: 'הקובץ גדול מדי, נסו קובץ עד 8MB',
        unsupportedFileType: 'סוג קובץ לא נתמך, נסו JPG, PNG, WebP או PDF',
        rescan: 'סריקה מחדש',
        selectAll: 'בחר הכל',
        clearAll: 'נקה הכל',
        removeItem: 'הסרה',
        emptyAfterScan: 'לא זוהו פריטים בקבלה',
        confirmButton: 'הוספה למזווה',
        cancelButton: 'ביטול',
        saveSuccess: 'הפריטים נוספו למזווה',
        saveError: 'הוספת הפריטים נכשלה, נסה שוב',
        urlLabel: 'קישור לקבלה או לעמוד הקנייה',
        urlPlaceholder: 'https://...',
        urlSubmit: 'ייבוא',
        urlError: 'לא הצלחנו לחלץ פריטים מהקישור',
        urlFallback: 'ניתן להזין את הפריטים ידנית במקום או לנסות קישור אחר',
        textFallback: 'ניתן להזין את הפריטים ידנית במקום או לנסות טקסט אחר',
        manualEntryLink: 'הוספה ידנית',
        pasteLinkSubtitle: 'הדביקו קישור לקבלה דיגיטלית - נזהה את המוצרים אוטומטית.',
        pasteTextSubtitle: 'הדביקו את שורות הקבלה - נזהה מוצרים, כמויות ומיקום.',
        pasteTextLabel: 'טקסט הקבלה',
        pasteTextPlaceholder: 'הדביקו כאן את שורות הקבלה, למשל:\nעגבניות שרי 1 ק"ג\nחזה עוף 0.9 ק"ג\nיוגורט ביו x4',
        pasteSubmit: 'זיהוי מוצרים',
        pasteTextError: 'לא הצלחנו לחלץ פריטים מהטקסט'
    },
    editForm: {
        title: 'עריכת מוצר',
        submit: 'שמירת שינויים',
        submitting: 'שומר...',
        suggestButton: 'קבל המלצת אחסון',
        suggesting: 'בודק המלצת אחסון...',
        saveError: 'שמירת השינויים נכשלה, נסה שוב',
        saveSuccess: 'השינויים נשמרו',
        deleteButton: 'מחק מוצר',
        deleting: 'מוחק...',
        deleteError: 'מחיקת המוצר נכשלה, נסה שוב',
        deleteSuccess: 'המוצר נמחק'
    },
    deleteDialog: {
        title: 'למחוק את המוצר?',
        description: 'הפעולה תמחק את המוצר מהמזווה לצמיתות. לא ניתן לבטל.',
        cancel: 'ביטול',
        confirm: 'מחיקה'
    }
} as const
